import {
  adjustStructureLearning,
  bindBenchmarkSongFile,
  getLatestTelemetry,
  loadFileSourceConfig,
  loadBenchmarkSongFileSource,
  getLatestTimingState,
  runBenchmarkSongTest,
  runListeningTest,
  saveFilterSetupEvaluation,
  saveFileSourceConfig,
  saveLearningEvaluation,
  startAudioStream,
  startListeningPipeline,
  startVideoRender,
  stopListeningPipeline,
  stopAudioStream,
  stopVideoRender,
} from "../services/tauriApi";

export const pipelineEngine = {
  input: {
    start: startAudioStream,
    stop: stopAudioStream,
  },
  listening: {
    start: startListeningPipeline,
    stop: stopListeningPipeline,
    runTest: runListeningTest,
    getLatestTimingState,
    getLatestTelemetry,
    loadFileSourceConfig,
    loadBenchmarkSongFileSource,
    saveFileSourceConfig,
    bindBenchmarkSongFile,
    runBenchmarkSongTest,
    adjustStructureLearning,
    saveLearningEvaluation,
    saveFilterSetupEvaluation,
  },
  output: {
    start: startVideoRender,
    stop: stopVideoRender,
  },
};
